export const SUCCESS_CODE = 0;
export const ERROR = {
  AUTH: {
    MISSING_EMAIL: 1,
    MISSING_PASSWORD: 2,
    INVALID_EMAIL: 3,
    WEAK_PASSWORD: 4,
    NOT_REGISTER_YET: 5,
    MISSING_NAME: 6,
    EMAIL_ALREADY_EXIST: 7,
    INCORRECT_PASSWORD: 9,
  },
};
